##Análisis leyes del Congreso

```{r}
library(stringr)
library(survival)
```

##### Cargar data

```{r}
#Cargar data:
data=read.csv("dfall.csv", stringsAsFactors = F)
head(data)
```

```{r}
names(data) #Variables: 
```

###Congreso: 

```{r}
#Nombre legislaturas
names(table(data$congreso))
```

```{r}
#Recodificar
data$congresoRec[data$congreso == names(table(data$congreso))[1]] = "1995-2000"
data$congresoRec[data$congreso == names(table(data$congreso))[2]] = "2001-2006"
data$congresoRec[data$congreso == names(table(data$congreso))[3]] = "2006-2011"
data$congresoRec[data$congreso == names(table(data$congreso))[4]] = "2011-2016"
data$congresoRec[data$congreso == names(table(data$congreso))[5]] = "2011-2016"
data$congresoRec[data$congreso == names(table(data$congreso))[6]] = "2016-2021"
```

```{r}
table(data$congresoRec)
#Mayor número de leyes en el periodo 2001-2006
```

### Fecha presentacion 
```{r}
#Fecha presentación: 
data$fechaPresentacion = str_trim(substr(data$fechaPresentacion,1,8))
data$fechaPresentacion = as.POSIXct(data$fechaPresentacion,format="%d/%m/%y")
```

### Fecha ultimo estado
```{r}
#Ponemos fecha HOY a espacios en blanco:
fechaHOY = format(Sys.time(), "%d/%m/%y") 
data$estadoFinalFecha[data$estadoFinalFecha == ""]= fechaHOY

data$estadoFinalFecha = str_trim(substr(data$estadoFinalFecha,1,8))
data$estadoFinalFecha = as.POSIXct(data$estadoFinalFecha,format="%d/%m/%y")
```

### Semanas ultimo estado

```{r}
#diferencia semanas entre inicio y fin 
data$Semanas = difftime(data$estadoFinalFecha,data$fechaPresentacion, units="weeks")
```

```{r}
#FILTRO. No incluir casos en los que la fecha fin sea anterior a la fecha incio (297 casos)
data = data[!data$Semanas < 0,]
```

### Leyes Publicadas 

```{r}
#Leyes publicadas
data$Publicado = ifelse(grepl("Publicado",data$estadoFinal),1,0)
```

###Multipartidario

```{r}
data$Multipartidario = ifelse(data$grupoParlamentario=="Multipartidario",1,0)
```

###Propone Ejecutivo

```{r}
data$propEjecutivo = as.factor(ifelse(grepl("Ejecutivo",data$proponente),1,0))
```

###Análisis

Creación del objeto survival:

```{r eval=F}
data$survival=with(data,Surv(Semanas, Publicado))
# que es:
head(data$survival,20)
```

Regresión Cox:

```{r eval=F}
modelo <- coxph(survival ~ congresoRec + Multipartidario + propEjecutivo,data=data)
summary(modelo)
```
